### ISSUE TITLE
[v50] Prevents connecting to other lobbies

### ISSUE THREAD

**Issue by viiuan** [Owen3H/IntroTweaks#10]
I will need to get some logs that can hopefully help diagnose the issue, but when using this mod at least on v50, it completely prevents me from connecting to other lobbies, at least ones where the host also has the mod. This was tested using modpack profile codes so all needed settings and required mods were present. Removing IntroTweaks on both ends fixed this.
Very confusing as I have no idea how an intro skip mod would affect networking

**Comment by NakiriFox** [comment]
I can enter other lobbies normally.

**Comment by viiuan** [comment]
I guess I can try to get some logs of this happening, if it even still happens. Just with the setup at that time and troubleshooting, it seemed that having this enabled was the culprit. I don't know what would happen using just IntroTweaks and entering a public lobby but between two people with the exact same mod profile it was having this issue with the mod enabled
Sorry about not even having logs ready in the first place. IDK why I didn't include any :/

Edit: I won't lie that I am getting an incredible ADHD mental block about the idea of testing it so I'll just close this issue as not completed for now.
