### ISSUE TITLE
[Compatiblity] Placement of menu items from other mods is off

### ISSUE THREAD

**Issue by YoBii** [Owen3H/IntroTweaks#2]
Since the latest update certain elements in menu that come from other mods are not positioned _correctly_. 

I guess they are simply placed and don't respect/not aware of your latest changes to the layout, anchors etc.

Here's a screenshot. Mod settings is from LethalExpansion, the version number in bottom left is from MoreCompany. I'm not using your version number option because it hides the LE version I think.

![image](https://github.com/Owen3H/IntroTweaks/assets/22051355/4066a9cf-e8db-4342-bd7b-6ac170c5e1bb)

**Comment by YoBii** [comment]
There's also something happening with the elements from BetterSaves. They are usually not that pink
![image](https://github.com/Owen3H/IntroTweaks/assets/22051355/ec9ac3f4-0cbc-4b04-b77d-aedf818b12a3)

**Comment by YoBii** [comment]
Since it's probably not easy to deal with these types of incompatibilities I'd suggest providing an option to disable all changes to menu with your mod.

Frankly speaking I'm using your mod because I want to skip the intro. I am not exactly expecting it to change menus and I doubt most people that install the mod are since it's called IntroTweaks not MenuTweaks.

**Comment by Owen3H** [comment]
Thank you for the report and screenshots. Mod incompatibilities were definitely an oversight, I will begin making a patch that provides config options to allievate these issues.

As for the LE version, they are directly editing the original version text which shouldn't be done. You should ask them to clone it instead as IntroTweaks hides the original.

**Comment by Owen3H** [comment]
Released [v1.3.1](https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/) which should solve the LE "mod settings" button and MoreCompany cosmetics button.
