### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by execOQ** [Owen3H/IntroTweaks#3]
Hello. I downloaded the latest version (1.4.0) and it looks like IntroTweaks can't find the objects it needs based on errors.

[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
IntroTweaks.Patches.MenuManagerPatch.ReplaceVersionText (MenuManager __instance) (at <6cadbfe2078c40ee956d69a69d714a3a>:IL_0030)
(wrapper dynamic-method) MenuManager.DMD<MenuManager::Awake>(MenuManager)

[Error :IntroTweaks] Error getting button: ModSettingsButton
System.NullReferenceException: Object reference not set to an instance of an object
   at IntroTweaks.Patches.MenuManagerPatch.GetButton (UnityEngine.GameObject panel, System.String name) [0x0000c] in <6cadbfe2078c40ee956d69a69d714a3a>:IL_000C
[Debug :IntroTweaks] Aligned menu buttons.
[Error :IntroTweaks] System.NullReferenceException: Object reference not set to an instance of an object
   at IntroTweaks.Patches.MenuManagerPatch.RemoveCreditsButton (System.Collections.Generic.IEnumerable`1[T] buttons) [0x00080] in <6cadbfe2078c40ee956d69a69d714a3a>:IL_0080
   at IntroTweaks.Patches.MenuManagerPatch.StartPatch (MenuManager __instance) [0x0010c] in <6cadbfe2078c40ee956d69a69d714a3a>:IL_010C

Full log:
[LogOutput.log](https://github.com/Owen3H/IntroTweaks/files/13846137/LogOutput.log)

**Comment by Owen3H** [comment]
I have actually implemented a fix for this already that will be in the next version :)
It should be harmless, it's just because the LethalExpansion settings button wasn't found.

**Comment by execOQ** [comment]
oh, okay then :)

Shouldn't IntroTweaks create this button itself in this case? Or why is it looking for a button?

**Comment by Owen3H** [comment]
It looks for the button to check if it exists so it can be aligned with the other buttons.

**Comment by execOQ** [comment]
got it. then I'm waiting for a new version, since you fixed this bug :)
