### ISSUE TITLE
[SUGGESTION] Allow customisation of the logo on the menu.

### ISSUE THREAD

**Issue by Clark919** [Owen3H/IntroTweaks#4]
Hi there! Big fan of your mod. I run it in a relatively large [modpack ](https://thunderstore.io/c/lethal-company/p/TeamClark/TheMostLethalCompany/)and use the custom version number to inform my users what the current version of the pack is to help troubleshoot and sync versions, which is an ideal feature.

When it comes to suggestions for modpack creators, I'd like to suggest the possibility of having a custom logo element (that replaces LETHAL COMPANY) that that you can provide a template/specification for with the default version of the mod, but players can easily edit by just changing a .png file in the modpack, called `logo.png` or something similar. Ideally it would be any image that fits the dimensions you specify. Example attached if I wasn't clear with my explanation:
![image](https://github.com/Owen3H/IntroTweaks/assets/44264851/d4b7ac90-10b2-4b1f-b36e-2ae87735f2e5)

**Comment by Clark919** [comment]
To add to this, some other mods already edit this element (AdvancedCompany/MoreCompany come to mind), so overwriting those mods to avoid conflicts would be ideal.

**Comment by Owen3H** [comment]
> Hi there! Big fan of your mod. I run it in a relatively large [modpack ](https://thunderstore.io/c/lethal-company/p/TeamClark/TheMostLethalCompany/)and use the custom version number to inform my users what the current version of the pack is to help troubleshoot and sync versions, which is an ideal feature.
> 
> When it comes to suggestions for modpack creators, I'd like to suggest the possibility of having a custom logo element (that replaces LETHAL COMPANY) that that you can provide a template/specification for with the default version of the mod, but players can easily edit by just changing a .png file in the modpack, called `logo.png` or something similar. Ideally it would be any image that fits the dimensions you specify.

I'm not sure if this should really be something for IntroTweaks to handle, though it is simple enough so I will consider it.
Also, I appreciate the kind words <3

**Comment by Owen3H** [comment]
> To add to this, some other mods already edit this element (AdvancedCompany/MoreCompany come to mind), so overwriting those mods to avoid conflicts would be ideal.

Could you provide me those mods in question? Thanks

**Comment by Owen3H** [comment]
I will not be implementing this as I no longer want to continue developing this mod.
Please keep an eye out for forks and give your suggestion there. ❤️
