### ISSUE TITLE
Zeekers & Unity Skip Options Doesn't Work

### ISSUE THREAD

**Issue by Narobic** [Owen3H/IntroTweaks#5]
As the title says no matter if I set it to true/false, it still doesn't skip. It always plays the seekers & unity intro

**Comment by Owen3H** [comment]
There is a very good chance this is fixed in the next version as this was reported in the modding discord already.

I believe the issue is that if mod loading takes over 10 seconds, skipping is no longer called. 
I have replaced this with a more consistent check to see if a scene has been loaded.

**Comment by Owen3H** [comment]
Give **v1.4.1** a shot ;)
https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/
