### ISSUE TITLE
Volume gets set to 0 and keybinds reset

### ISSUE THREAD

**Issue by THomasHfds2** [Owen3H/IntroTweaks#6]
Mod still works and skips the intros, but every time I start the game modded my in-game volume gets set to 0 and my custom keybinds get reset. This started occurring right after the v47 update.

**Comment by Paradox75831004** [comment]
Yes, I just wanted to write about this, but they beat me to it xD

**Comment by Owen3H** [comment]
A fix is on its way :P
See 992006c40c25a9763acfe39f7fff11df64ad48f1.

**Comment by Owen3H** [comment]
Likely fixed in **v1.4.1**. Give it a shot and lmk, then I'll close this issue.
https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/

**Comment by THomasHfds2** [comment]
Yup it's fixed, thanks for creating and continuing to support this mod
