### ISSUE TITLE
Bug with logo and additional button shifting

### ISSUE THREAD

**Issue by Archer-Dante** [Owen3H/IntroTweaks#7]
If IntroTweaks used with MoreCompany, then bug appears

![oJ7ySsB](https://github.com/Owen3H/IntroTweaks/assets/7766366/d1e7b219-cd24-4b54-aeb7-7892e16cc3ab)

happened only after v47 update

**Comment by Owen3H** [comment]
I am aware of this and investigating, though I didn't know having MC actually fixes this. 🤔
Appreciate the report, will likely be fixed early morning GMT / late night CST.

**Comment by Owen3H** [comment]
Hey, I have just released **v1.4.2** and no longer seeing this issue, I'd appreciate if you could confirm it's fixed :^)
https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/

**Comment by Archer-Dante** [comment]
Fixed version works much better, but cosmetics button still moved out of screen

![0KzrRwN](https://github.com/Owen3H/IntroTweaks/assets/7766366/e80cda28-b74f-463e-8703-8c3c0a49aad5)

I've tried to set these:

bAlignMenuButtons = false
bFixMenuCanvas = false
bFixMenuPanels = false

but no luck
on v45 setting those to false fixed it

Maybe it also matters, but my screen has 16:10 aspect ratio

**Comment by Owen3H** [comment]
Hmm, aspect ratio could be the issue. Could I get your mod list (or profile) for reference?

**Comment by Archer-Dante** [comment]
I'm getting this even with only MoreCompany + IntroTweaks, without any other mods

**Comment by Owen3H** [comment]
I see. Have you tried MC on its own, without IntroTweaks?

**Comment by Archer-Dante** [comment]
Yes

That how it looks with MC only:
![3Sb7Iav](https://github.com/Owen3H/IntroTweaks/assets/7766366/1a9e47cc-7521-4215-9204-bd1fd9f334ad)

the plugin folder:
![mVEqLbg](https://github.com/Owen3H/IntroTweaks/assets/7766366/4b0ec1cb-2c14-4869-a1d3-2c78a107fa11)
_(MMHOOK & MoreCompanyCosmetics downloaded \ unpacked automatically)_

**Comment by Owen3H** [comment]
Someone else had mentioned an aspect ratio issue in the modding discord, so it's very likely that.
I suspect it's because the position is being altered directly, with no anchoring applied.

I will address this in v1.4.3 as well as the custom version text.

**Comment by Owen3H** [comment]
v1.4.3 introduced a fix for the version text.
While v1.4.5 slightly tweaks how the cosmetics buttons are positioned, I have decided that **MoreCompany** should handle how its UI elements are anchored to fix the aspect ratio/window resize issue with things like the buttons.
