### ISSUE TITLE
Wrong version number on V49

### ISSUE THREAD

**Issue by afisarsy** [Owen3H/IntroTweaks#8]
Instead of showing v49 (same as the game version), it shows v16391 instead.

**Comment by Owen3H** [comment]
You can change this in the config by setting `sVersionTextFormat` to "SHORT".

**Comment by afisarsy** [comment]
Did you mean "FULL"?

When I use "SHORT" its showing v16391
But when I use "FULL" it shows v49

**Comment by Owen3H** [comment]
Sorry for the delay, I have just released **v1.4.3** which replaces this setting with another one that makes a little bit more sense.
