### ISSUE TITLE
Lethal Level Loader compatibility issue.

### ISSUE THREAD

**Issue by HamedAlmanthari** [Owen3H/IntroTweaks#9]
hi. apparently IntroTweaks breaks [LethalLevelLoader](https://thunderstore.io/c/lethal-company/p/IAmBatby/LethalLevelLoader/) when using sAutoSelectMode because LLL loads assets on mode menu. Also, apparently LLL works fine with [LC FastStartup](https://thunderstore.io/c/lethal-company/p/flerouwu/LC_FastStartup/). it would be appreciated if you could fix this compatibilty issue just like LC FastStartup because i like how IntroTweaks makes the main menu look. i very much prefer to use IntroTweaks rather than LC FastStartup. ty!

**Comment by HamedAlmanthari** [comment]
the issues IntroTweaks would cause with LLL include: 
stuck at "random seed" screen when landing a second time after hosting. in my experience, this usually happened when i land on any moon a second time after hosting but it could be caused randomly idk.

**Comment by Owen3H** [comment]
Usually I am all for fixing incompatibilities on my end but in this case LLL has broken all skip mods and now implemented a feature to block skipping which just causes a black screen.

There is really no motive for me to work on this atm, all I can do is suggest LE / LECore.

**Comment by Owen3H** [comment]
I have managed to pretty much fix this with 562b6da.
That being said, I will still be defaulting `bAutoSelectMode` to `OFF` and providing a warning when LLL is detected.

**Comment by Owen3H** [comment]
[v1.4.6](https://thunderstore.io/c/lethal-company/p/Owen3H/IntroTweaks/versions/) is out.

**Comment by Owen3H** [comment]
This mod will no longer be maintained.
